# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProcapDriver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProcapDriver
	pod 'AFNetworking', '~> 3.0'
    pod 'NewRelicAgent', "~> 5"
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod "PubNub", "~> 4"
    pod 'SAMKeychain'

  target 'ProcapDriverTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'AFNetworking', '~> 3.0'
  end

  target 'ProcapDriverUITests' do
    inherit! :search_paths
    # Pods for testing
	pod 'AFNetworking', '~> 3.0'
  end

end
